[package]
name = "transit"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
# Dependencies to other legion crates must stay limited limited
derive-transit = { path = "derive", version = "0.1.0" }
################################################################################
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"

# can't use lgn-tracing, would cause a circular dependency
log = { version = "0.4", features = ["std"] }

[dev-dependencies]
memoffset = "0.6"
