[package]
name = "transit"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
derive-transit = { path = "derive", version = "0.1.0" }

serde.workspace = true
anyhow.workspace = true

# can't use lgn-tracing, would cause a circular dependency
log.workspace = true

[dev-dependencies]
memoffset.workspace = true
