[package]
name = "lgn-test-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
micromegas-tracing.workspace = true
parking_lot = "0.12.0"
tempfile = "3.2"
