[package]
name = "micromegas"
description = "Micromegas is a scalable observability solution."
keywords = ["observability", "telemetry", "analytics"]
readme = "README.md"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mm-ingestion.workspace = true
