[package]
name = "telemetry-admin"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-blob-storage.workspace = true
tracing.workspace = true
lgn-telemetry-proto.workspace = true
telemetry-sink.workspace = true
analytics.workspace = true
transit.workspace = true
clap.workspace = true
tokio.workspace = true
sqlx.workspace = true
anyhow.workspace = true
prost.workspace = true
lz4.workspace = true
json.workspace = true

[dev-dependencies]
lgn-test-utils = { path = "../lgn-test-utils" }
fs_extra = "1.2"
