[package]
name = "telemetry-ingestion-srv"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
default-run = "telemetry-ingestion-srv"

[dependencies]

lgn-blob-storage.workspace = true
lgn-telemetry-proto.workspace = true
telemetry-sink.workspace = true
tracing.workspace = true
transit.workspace = true

anyhow.workspace = true
axum.workspace = true
bytes.workspace = true
chrono.workspace = true
ciborium.workspace = true
clap.workspace = true
http.workspace = true
hyper.workspace = true
prost.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tonic.workspace = true
tower-http.workspace = true
whoami.workspace = true

[[bin]]
name = "telemetry-ingestion-srv"
path = "src/main.rs"

[[bin]]
name = "telemetry-generator"
path = "test/generator.rs"
