[workspace]
members = ["*"]
exclude = ["target"]
resolver = "2"

[workspace.dependencies]
lgn-auth = { path = "lgn-auth" }
lgn-blob-storage = { path = "lgn-blob-storage", version = "0.1.0" }
lgn-telemetry-proto = { path = "lgn-telemetry-proto" }

telemetry-sink = { path = "telemetry-sink" }
tracing = { path = "tracing" }
transit = { path = "transit" }

axum = "0.7.4"
bytes = "1.1"
ciborium = "0.2.2"
clap = { version = "3.0", features = ["derive"] }
http = "0.2"
hyper = "0.14"
tonic = "0.6"
tokio = { version = "1.13", features = [
    "macros",
    "rt-multi-thread",
    "tracing",
] }
whoami = "1.2"
anyhow = "1.0"
sqlx = { version = "0.5", features = [
    "sqlite",
    "any",
    "mysql",
    "runtime-tokio-native-tls",
] }
tower-http = { version = "0.5.2", features = ["limit"] }
chrono = "0.4"
prost = "0.9"
serde_json = "1.0"
