[package]
name = "telemetry-sink"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgn-telemetry-proto.workspace = true
tracing.workspace = true
transit.workspace = true
lgn-config.workspace = true

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
ciborium.workspace = true
colored = {workspace = true, optional = true}
ctrlc.workspace = true
lazy_static.workspace = true
log.workspace = true
once_cell.workspace = true
prost.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
time = {workspace = true, optional = true}
tokio.workspace = true
tonic.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
atty.workspace = true
winapi.workspace = true

[features]
default = ["colors", "timestamps"]
colors = ["colored"]
timestamps = ["time"]
stderr = []

max_level_off = ["log/max_level_off", "tracing/max_level_off"]
max_level_error = ["log/max_level_error", "tracing/max_level_error"]
max_level_warn = ["log/max_level_warn", "tracing/max_level_warn"]
max_level_info = ["log/max_level_info", "tracing/max_level_info"]
max_level_debug = ["log/max_level_debug", "tracing/max_level_debug"]
max_level_trace = ["log/max_level_trace", "tracing/max_level_trace"]

release_max_level_off = [
    "log/release_max_level_off",
    "tracing/release_max_level_off",
]
release_max_level_error = [
    "log/release_max_level_error",
    "tracing/release_max_level_error",
]
release_max_level_warn = [
    "log/release_max_level_warn",
    "tracing/release_max_level_warn",
]
release_max_level_info = [
    "log/release_max_level_info",
    "tracing/release_max_level_info",
]
release_max_level_debug = [
    "log/release_max_level_debug",
    "tracing/release_max_level_debug",
]
release_max_level_trace = [
    "log/release_max_level_trace",
    "tracing/release_max_level_trace",
]

max_lod_off = ["tracing/max_lod_off"]
max_lod_min = ["tracing/max_lod_min"]
max_lod_med = ["tracing/max_lod_med"]
max_lod_max = ["tracing/max_lod_max"]

release_max_lod_off = ["tracing/release_max_lod_off"]
release_max_lod_min = ["tracing/release_max_lod_min"]
release_max_lod_med = ["tracing/release_max_lod_med"]
release_max_lod_max = ["tracing/release_max_lod_max"]
