[package]
name = "telemetry-sink"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgn-auth = { path = "../lgn-auth", version = "0.1.0" }
lgn-telemetry-proto = { path = "../lgn-telemetry-proto", version = "0.1.0" }
tracing = { path = "../tracing", version = "0.1.0" }
transit = { path = "../transit" }
lgn-online = { path = "../lgn-online" }
lgn-config = { path = "../lgn-config" }
anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4"
colored = { version = "2", optional = true }
ctrlc = "3.2.0"
lazy_static = "1.4"
log = { version = "0.4", features = ["std"] }
once_cell = "1.7.2"
prost = "0.9"
time = { version = "0.3.5", features = [
    "formatting",
    "local-offset",
    "macros",
], optional = true }
tokio = { version = "1.13", features = ["full"] }
tonic = "0.6"
uuid = { version = "1.0", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
atty = "0.2.13"
winapi = { version = "0.3", features = ["handleapi", "winbase"] }

[features]
default = ["colors", "timestamps"]
colors = ["colored"]
timestamps = ["time"]
stderr = []

max_level_off = ["log/max_level_off", "tracing/max_level_off"]
max_level_error = ["log/max_level_error", "tracing/max_level_error"]
max_level_warn = ["log/max_level_warn", "tracing/max_level_warn"]
max_level_info = ["log/max_level_info", "tracing/max_level_info"]
max_level_debug = ["log/max_level_debug", "tracing/max_level_debug"]
max_level_trace = ["log/max_level_trace", "tracing/max_level_trace"]

release_max_level_off = [
    "log/release_max_level_off",
    "tracing/release_max_level_off",
]
release_max_level_error = [
    "log/release_max_level_error",
    "tracing/release_max_level_error",
]
release_max_level_warn = [
    "log/release_max_level_warn",
    "tracing/release_max_level_warn",
]
release_max_level_info = [
    "log/release_max_level_info",
    "tracing/release_max_level_info",
]
release_max_level_debug = [
    "log/release_max_level_debug",
    "tracing/release_max_level_debug",
]
release_max_level_trace = [
    "log/release_max_level_trace",
    "tracing/release_max_level_trace",
]

max_lod_off = ["tracing/max_lod_off"]
max_lod_min = ["tracing/max_lod_min"]
max_lod_med = ["tracing/max_lod_med"]
max_lod_max = ["tracing/max_lod_max"]

release_max_lod_off = ["tracing/release_max_lod_off"]
release_max_lod_min = ["tracing/release_max_lod_min"]
release_max_lod_med = ["tracing/release_max_lod_med"]
release_max_lod_max = ["tracing/release_max_lod_max"]
