[package]
name = "analytics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lgn-blob-storage.workspace = true
tracing.workspace = true
transit.workspace = true
telemetry-sink.workspace = true
lgn-telemetry-proto.workspace = true
ciborium.workspace = true
sqlx.workspace = true
anyhow.workspace = true
prost.workspace = true
serde_json.workspace = true
async-recursion.workspace = true

[dev-dependencies]
telemetry-sink.workspace = true
