[package]
name = "analytics"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-blob-storage = { path = "../lgn-blob-storage"  }
tracing = { path = "../tracing"  }
transit = { path = "../transit"  }
telemetry-sink = { path = "../telemetry-sink"  }
lgn-telemetry-proto = { path = "../lgn-telemetry-proto"  }
ciborium = "0.2.2"
sqlx = { version = "0.5", features = [
    "sqlite",
    "any",
    "mysql",
    "runtime-tokio-native-tls",
] }
anyhow = "1.0"
prost = "0.9"
serde_json = "1.0"
async-recursion = "1"

[dev-dependencies]
telemetry-sink = { path = "../telemetry-sink" }
