[package]
name = "ingestion"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
chrono.workspace = true
ciborium.workspace = true
object_store.workspace = true
serde_json.workspace = true
sqlx.workspace = true
telemetry-sink.workspace = true
tracing.workspace = true
transit.workspace = true
url.workspace = true

